/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package spark.basic

import spark.basic.example.RDDExample
import spark.basic.init.InitSpark


object App extends InitSpark {
  def main(args: Array[String]): Unit = {
    val example = new RDDExample
    example.operationExample(sc)
  }
}
